name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - name: Build
        run: zig build install --release=safe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zig-library
          path: zig-out/lib/*
      - name: Debug output paths 
        run: ls -R

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: zig-library
          path: zig-out/lib
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: zig-out/lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

